@api = http://localhost:3000/api/usuarios
@api10 = "https://apirestseimalsa-production.up.railway.app/api/usuarios"


{{api}}

###
http://localhost:3000/api/activos/VLTJ33CA

### add a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "product 2",
   "description": "some product",
   "quantity": 10
}

### get product
POST {{api}}/login
Content-Type: application/json

{
    "USU_usuario": "admin",
    "USU_clave": "admin"
}

###
POST {{api10}}/login
Content-Type: application/json

{
    "USU_usuario": "csierra",
    "USU_clave": "csierra"
}

### delete product 
DELETE {{api}}/772

### get count
{{api}}/count

### update
PUT {{api}}/767
Content-Type: application/json

{
    "name": "laptop",
    "description": "some laptop",
    "quantity": "20"
}

@api10 = http://localhost:3000/api/info

### post correo
POST {{api10}}
Content-Type: application/json

{
    "documento": "0911615557",
    "captcha": "03AL8dmw882ZXZ5Rx6Gid7qn_6Zj4t9fseq9qqG7pcKfkxK0Hcrx2iEvsvrcvWYz03y6I-zGXvppRLXP-mFlJeUu3VLXvkel0ZE-sYguUAbDu6T2IwREtUlXVLAOuqID6O9447wUH9wddqduspeJnDhKlM2meQ09Kr7cHHkmcguQq-zG8zbC93cWuHuoPfeCWNiboGfPsRUaCoA72vMk7N_VBJPkcQkYXZ1Ox_1RupceXJP3J5oj9rUD2tgYoP5p57nLVrpWAF6sSBphGGNm5ZLNvw1ZZuQjSTVE56zQ9vx7SCA0DhhCiZdE68GwzTW0ZP3QllH2vWaTsgHtNMdIHBhQLIyJ3UpgBTNrhKHIAGJuOihZJUXI8myorZyrCnOcld40bsnGdTiwbuA4xlfmeggEPDKq-ub3a1wC2Y3TpE9hwRW6Qg8zcHPiLAU9KxN7bGwbVGFij6sOi37FP2BEqGI5C53YBh6niPro4li_gvVBQ5Cnz9f43JLPy4Fn3RUrbseM8WjmXj3dXbbyu3Tl3Nf3AYJrVOrqcczhb2PC1bfJa6Ji9nzc6-TfU"
}