@api = http://localhost:3000/api/usuarios
@api10 = "https://apirestseimalsa-production.up.railway.app/api/usuarios"


{{api}}

###
http://localhost:3000/api/activos/VLTJ33CA

### add a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "product 2",
   "description": "some product",
   "quantity": 10
}

### get product
POST {{api}}/login
Content-Type: application/json

{
    "USU_usuario": "admin",
    "USU_clave": "admin"
}

###
POST {{api10}}/login
Content-Type: application/json

{
    "USU_usuario": "csierra",
    "USU_clave": "csierra"
}

### delete product 
DELETE {{api}}/772

### get count
{{api}}/count

### update
PUT {{api}}/767
Content-Type: application/json

{
    "name": "laptop",
    "description": "some laptop",
    "quantity": "20"
}

@api10 = http://localhost:3000/api/info

### post correo
POST {{api10}}
Content-Type: application/json

{
    "documento": "0911615557",
    "captcha": "03AL8dmw93zeocLQ2YZZwkK0D0v-6i403_9cYIYPiOwEv8s2uY6Lxz1UPfZBZ-UxOZy7BKG3jOj-r_eiD4sYPYvfd-eRjwD9LuGo2Z5Ue0kgZy-aRD5mxKyrUJLt_U_N3CcBUjh7lijH8sqvQBZzMoY5mbixRv05SOMXj7VxrzfaTvwskBySGR-EFCSWGqkRHDN29kxjmA6U6NCGk67z8s9o3eSvmjJXSDsKUVXK0odOD273bfn7ffwdFGRLuH2P2vbgjPqh7TTKELK27ovd-tKjBSpMEBauMfwtUOknQBQ8Hwntz7fu41BrjIaefvK0fP9kg7hdqmUrgb-gPXc34j3vDg0beDcX_UIHLxtHmPccgTpLBC5oBCGNEvuHfz6xIVFOZn0fhegLdpKHDLTIpCBNoknkLie3-rvW96vJZm8CxrnDaSojlEiFzD5fEtPHmJo9oeQY0sgA4PqrE_35kVHN9YLrT3gMyJws_qkSt-dKrt3-5jzk8SQup_jFa3v9Fx67qBwFTeh6AcG2FTpF4trLomMLYcRXOrY_uoDmb6qo3jpVArva1B7QzbqGqHz_p9Pjv4b6ZsZ-V2"
}